### ISSUE TITLE
Camera rotate reset

### ISSUE THREAD

**Issue by Michael0933** [Gh0stBlade/KAIN2#1403]
Camera keeps reset its rotation anytime movement occur.

After rotating camera:
![2024-03-23 22_25_33-Legacy of Kain_ Soul Reaver - OpenGL 3 3 - v0 7 - 32-bit](https://github.com/Gh0stBlade/KAIN2/assets/6887483/38fc23c2-5a9a-4250-8513-bd5eebcde9c8)

After any movement:
![2024-03-23 22_25_41-Legacy of Kain_ Soul Reaver - OpenGL 3 3 - v0 7 - 32-bit](https://github.com/Gh0stBlade/KAIN2/assets/6887483/1befa919-657e-457c-96d3-422b30e07e5b)

**Comment by FedericoMilesi** [comment]
Just added a quick fix to this issue, however the issue will still remain open because my fix involves commenting out CAMERA_DoCameraCollision2 and that can't really be the solution. My guess is that it occurs because CAMERA_ACNoForcedMovement (which gets called a lot on the bounties list) needs implementation.
